name: Renew Music User Token (Weekly)

on:
  schedule:
    # - cron: '0 0 * * 0' // Weekly
    - cron: '*/5 * * * *'
  workflow_dispatch:

env:
  SITE_URL: 'https://shick.io'

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Renew music user token
        env:
          ENV_VAR_KEY: 'TEST_VARIABLE'
          SITE_TOKEN: ${{ secrets.SITE_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: ./scripts/renew-music-user-token.mjs
