name: Renew Music User Token (Daily)

on:
  workflow_dispatch:
  schedule:
    - cron: '5 14 * * *'

env:
  SITE_URL: 'https://shick.io'
  VERCEL_PROJECT_NAME: 'shick-io'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Renew music user token
        env:
          SITE_TOKEN: ${{ secrets.SITE_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          ./scripts/renew-music-user-token.ts
